---
- name: Install
  hosts: all
  become: true
  become_method: ansible.builtin.sudo

  vars:

    redis_config:
    - key: bind
      value: "0.0.0.0"
    - key: protected-mode
      value: "no"
    - key: port
      value: "6379"
    - key: requirepass
      value: "r3dis-s3cr3t"

  pre_tasks:
  - name: check for file custom_vars.yml
    ansible.builtin.stat:
      path: custom_vars.yml
    register: stat_custom_vars
  - name: load custom vars, if existent
    ansible.builtin.include_vars:
      file: custom_vars.yml
    when: stat_custom_vars.stat.exists

  roles:
  - name: andrelohmann.root_colored_prompt
  - name: ansible-role-redis

...
